"""update tables

Revision ID: 191e40066f8b
Revises: e2ee0b23a9e1
Create Date: 2023-07-08 23:55:35.891274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191e40066f8b'
down_revision = 'e2ee0b23a9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'created_at')
    # ### end Alembic commands ###
