"""update tables

Revision ID: 25f9a47b69e4
Revises: b51bfe9bd95b
Create Date: 2023-07-09 04:32:29.130502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f9a47b69e4'
down_revision = 'b51bfe9bd95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'name')
    # ### end Alembic commands ###
