"""empty message

Revision ID: 35d0a6154c7e
Revises: 
Create Date: 2023-07-05 13:50:36.173594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d0a6154c7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shopname', sa.VARCHAR(length=25), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('logo_banner', sa.VARCHAR(), nullable=True),
    sa.Column('profile_photo', sa.VARCHAR(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('shopname')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('profile_photo', sa.VARCHAR(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.INTEGER(), nullable=False),
    sa.Column('rollover_period', sa.INTEGER(), nullable=True),
    sa.Column('last_rollover', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_items_seller_id_sellers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_favorites_item_id_items')),
    sa.ForeignKeyConstraint(['shop_id'], ['sellers.id'], name=op.f('fk_favorites_shop_id_sellers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('options', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_form_items_item_id_items')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_orders_item_id_items')),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_orders_seller_id_sellers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('form_items')
    op.drop_table('favorites')
    op.drop_table('items')
    op.drop_table('users')
    op.drop_table('sellers')
    # ### end Alembic commands ###
