"""changes to favorites

Revision ID: 41dcf3aeac4b
Revises: 9bc55c197bfb
Create Date: 2023-07-15 22:18:03.834765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dcf3aeac4b'
down_revision = '9bc55c197bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_favorites_shop_id_sellers', 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'shop_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('shop_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_favorites_shop_id_sellers', 'favorites', 'sellers', ['shop_id'], ['id'])
    # ### end Alembic commands ###
